### ISSUE TITLE
例子里的 remove_document 执行返回错误

### ISSUE THREAD

**Issue by zhangchunlin** [newpanjing/gofound-python#3]
gofound版本： 9b0b2048e8d628e82fbe0de1a045c944a214e5a4
gofound-python 1.1.2和pip安装的1.1.3都试过了，例子代码里的 remove_document 返回错误
```
Traceback (most recent call last):
  File "/home/zhangclb/sandbox/gofound/gofound-python/tests.py", line 59, in <module>
    remove()
  File "/home/zhangclb/sandbox/gofound/gofound-python/tests.py", line 52, in remove
    res = client.remove_document(1000)
  File "/home/zhangclb/sandbox/gofound/gofound-python/gofound/client.py", line 60, in remove_document
    "id": id
  File "/home/zhangclb/sandbox/gofound/gofound-python/gofound/client.py", line 24, in _post
    raise Exception("Error:", res.status_code)
Exception: ('Error:', 404)
```

**Comment by zhangchunlin** [comment]
我最后发现应该是gofound的问题，在 admin 页面里删除也是失败了
